### ISSUE TITLE
disable forwarder agent from splunk web console

### ISSUE THREAD

**Issue by prashantnitt07** [splunk/splunk-ansible#117]
hi , 
Need to disable disable forwarder agent from splunk web console

pleae suggest

**Comment by nwang92** [comment]
@prashantnitt07 I'm not certain I follow your question. If Splunk instance "so1" is forwarding to Splunk instance "so2", do you want to disable forwarding from the web UI on "so1" or "so2"?

**Comment by nwang92** [comment]
Not sure if you resolved your issue or not, but you can disable/enable forwarding on the UI via `http://<hostname>:<splunk-web-poort>/en-US/manager/launcher/data/outputs/tcp/server`.

On the Splunk instance that is sending logs to a remote standalone/indexer, navigate to that URL and you should have control on disabling the forwarding. This is also accessible via Settings > Forwarding and Receiving.

Note this is not possible on the universal forwarder because there's no web UI. I'm going to close this issue due to inactivity, but feel free to drop a reply if you have any lingering questions.
