### ISSUE TITLE
need  pointers on how to use this repository for provisioning remote and non-docker instances

### ISSUE THREAD

**Issue by kundeng** [splunk/splunk-ansible#128]
I traced the code and tried to figure out how to best use this repository for non-docker based environment,  but I'm still confused. 

The splunk-docker project seems to be using this project in the following way:
1. bake the ansible scripts (as well as ansible and python etc) all into docker image. 
2.  pass default.yml into the container
3.  pass environment variables into container
4.  container entrypoint call ansible with dynamic inventory 
5.  the dynamic inventory script merges  baked defaults with default.xml and with environment variables
6.  ansible runs local-connection on site.yml. 
7.  each docker container has the full information as how to provision itself along with information to talk to  splunk on other docker containers.  

Our environment is not docker-based.   I would appreciate if splunk provides a wrapper or at least pointers how to use this repository for non-docker based environment. 

Will the following idea work? 

1. a wrapper ansible playbook. 
a. install prerequisite such as ansible python .. on all hosts.  
b. copy or download entire repository onto each host.   
c  run ansible with site.yml and dynamic inventory script for each host (maybe  using delegate_to? ) as a task:
  c1.  pass  ansible's env as env to each host in that task. 
d.  remove remote ansible and python.

each task in each step c basically simulates a service in docker-compose.yml.  

Are there any better ways to do this?  The above seems to be very ugly. 
Especially step c---  I don't know whether that's even possible or not.

**Comment by lephino** [comment]
@nwang92 just updated the documentation in develop with how to use it.  Have you taken a look at it yet?  If so, where are you getting stuck? https://github.com/splunk/splunk-ansible/blob/develop/docs/SETUP.md

**Comment by kundeng** [comment]
Can you please read my question?  Our environment doesn't support docker.  The ansible script is developed for  running with local-connections.  That is on each host (virtual or physical), ansible and python need to be installed.  My question is how to best organize the ansible playbook(s) to utilize this repository without reinventing the wheels.

**Comment by lephino** [comment]
Not sure how to respond to this... those instructions are for running without docker.  It uses the docker container simply to show you how it works before you setup a bare metal host. You’ll see in the prereqs, In no way is docker required.  Read the setup section and install the prereqs and then copy in defaults.yml and the Splunk ansible files. If it says docker copy you use scp; where it says docker run, you just run the command example: cd /tmp/splunk-ansible; ansible-playbook --connection local site.yml --extra-vars "@default.yml"'

**Comment by SkyKnightSKS** [comment]
Hello Kundeng, we use the ansible playbooks on a non-docker environment as well.
The simplest way to do this would be to edit site.yml and change localhost into ALL.
Make your standard inventory file where you define all the different hosts.
And add one additional task using the feature: ansible_pre_tasks
This additional task would be to copy over the splunk binary.

This method of working only requires you to have either SSH keys or SSH passwords configured for all the hosts.
You can run these plays from a workstation or an ansible tower.

**Comment by kundeng** [comment]
Thank you both for your reply.  

Lephino,
In that documentation, it say explicitly the following,
This codebase is meant to be used via local connection, which brings up the node you run the ansible-playbook command on as a full-fledged Splunk instance.  

However, even after I read it,  I don't think your suggestion would work well for me.   I can't use local-connection like that in your example.  
cd /tmp/splunk-ansible; ansible-playbook --connection local site.yml --extra-vars "@default.yml"'
Because that would require me  to run the command 50 splunk instances manually, on each instance itself. 

SkyKnightSKS,  can you further explain or share your code? 
If I understand,  your suggestion is 
1> bypass the dynamic inventory 
2> use static inventory.   Can you care to share how you merge the per-host specific environment variable with the default.yml? 

For instance,  the dynamic inventory does the following:
defaultVars["splunk"]["license_master_included"] = True if os.environ.get('SPLUNK_LICENSE_MASTER_URL', False) else False

Do you just put  this value splunk.license_master_included in that host's  host-var?

**Comment by SkyKnightSKS** [comment]
kundeng, yes, the dynamic inventory file is very much docker oriented and my opinion is that this maybe belongs in the docker git instead.
I have written my own inventory script, this queries a service-now asset database and outputs the same layout the dynamic inventory script does.

In #123 I will write more details later to easier support the exact same thing what you are trying to do.  For now it works but all variables need to be specified on host base and not on groups.

For the license master particularly I kind of omit that setting and use splunk.conf part to set splunk.conf.server.license.master_uri.

**Comment by lephino** [comment]
We actually envisioned that most people would have a central node for running ansible / managing your inventory.  Since everyone's environment / technology is different, we wanted to settle on 1 set way to allow configurations to be semi-dynamic.  The reason for ENV vars, was to support baremetal, ec2 vm's, k8 and docker. We then envisioned something like ansible tower / Ansible awx (https://github.com/ansible/awx) control your inventory / host control or some sort of operator (aws, docker ucp, openshift, open-stack, vsphere).  This inventory / runner node would then simply set the ENV correctly for the host using a host fact and pass in a simple play that just is the exec calling ansible-playbook command on the remote node.  The fundamental difference between how @SkyKnightSKS / you're asking to run this repo, is to have that central node actually run every play vs having the remote node handle itself.  From our inception, it was to allow people who didn't invest in ansible / knowledge of ansible or in ansible tower to also succeed.

From a performance side, we found when you're spinning up large clusters (50-500 nodes), running in a sequential manner just takes forever (48min ish on 500 nodes), while having each node run in this more "async" style allows a cluster of any-size to always be done in the rough time-window (30s to 10min depending on your hardware).  Due to that time difference, this repo basically assumes you'll use more of a "delegation_to" type declaration (https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#delegation) on a simple playbook that's basically an ansible exec "ansible-playbook --connection local site.yml --extra-vars "@default.yml"'", and then the node sets itself us.

If you guys don't like that style of declaration, you're more than welcome to submit another inventory script into this repo, and add the documentation for running it in a remote connection style.  The scripts themselves and plays should mostly work, as these plays actually came out of a system that functioned identically to what you're asking for.  I don't see anything wrong with this repo supporting both run/connection styles and being able to toggle between them.

**Comment by lephino** [comment]
Would it be beneficial if I create an example of how to use splunk-ansible on a small scale, and using nothing but ansible?  I'll probably use like 4 alpine nodes with ssh just to show an example that you can run, but please note it'd run on any node with ssh.

**Comment by SkyKnightSKS** [comment]
When using strategies you can run multiple hosts at the same time.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html
The default setting is indeed to run sequential.

ps: We are using the ansible-playbooks in different ways. One is to run it from a docker (self-contained), the other is running from a central point both with and without ansible installed locally.  Some environments we run in are hybrid VM/docker, in those environments we use a central component to connect to ssh for the vm and the docker socket for the containers.
https://docs.ansible.com/ansible/latest/plugins/connection/docker.html

**Comment by kundeng** [comment]
> Would it be beneficial if I create an example of how to use splunk-ansible on a small scale, and using nothing but ansible? I'll probably use like 4 alpine nodes with ssh just to show an example that you can run, but please note it'd run on any node with ssh.

That would be very helpful.   Please see my original question and step 1c.  I have a central ansible tower.  If I understand your method, you are suggesting an ansible playbook from tower that has mostly just  a delegate_to  task that invokes ansible on a remote host, optionally also passing environment variable etc.   Is that a correct interpretation?

**Comment by lephino** [comment]
work in progress: https://github.com/splunk/splunk-ansible/tree/ansible-wrapper/wrapper-example

Have some small stuff left to do, like mounting some volumes so splunk can actually start in a container, but it's at a point where you can actually see the intended use.

**Comment by lephino** [comment]
I should also state the "install-splunk.playbook" physically sets up every aspect needed for splunk-ansible.  It assumes you have a completely blank slate, with 0 packages pre-installed (yes it even installs ansible for you remotely)

**Comment by lephino** [comment]
PR opened: https://github.com/splunk/splunk-ansible/pull/130

And yeah, basically I just setup a group for each role, and then I set my env vars based on that role.  You could adjust these in host files, env facts etc.  I then set those prior to calling the ansible-playbook command, which you can either call async or call it using "delegate_to".  The sample I set, runs async so that you pull back all the logs and can have a running status of the remote process as it completes.  Let me know if it works for your use case!

**Comment by lephino** [comment]
Gonna close this issue, feel free to reopen if I didn't meet the use case.  I'd also call out, you could do this with puppet / by hand with an ssh wrapper etc.
