### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by compyy** [splunk/splunk-ansible#14]
Hi, Unable to find complete documentation for this code ? or i am missing something ?

**Comment by arctan5x** [comment]
Current documentation is: https://github.com/splunk/splunk-ansible/tree/master/documentation

**Comment by compyy** [comment]
yes i see the folder but i dont see actual document, about how to use this library, use cases, example there :)

**Comment by arctan5x** [comment]
Documentation is built here: https://splunk.github.io/splunk-ansible/

Because this project is tightly coupled with https://github.com/splunk/docker-splunk, it also helps to look at Docker-Splunk's documentation as well. We will continue to add documentation as we develop the project. Closing for now.
