### ISSUE TITLE
rpm installation option?

### ISSUE THREAD

**Issue by tod-uma** [splunk/splunk-ansible#175]
From what I see, the only option for installation on linux is the tgz version using these scripts. Was that a design decision, or just no one saw the need for .rpm or .deb? Would there be any interest in a pull request to allow the other formats?

**Comment by nwang92** [comment]
We opted for the tgz for simplicity - it also allows others to host their own splunk tarball and be able to use that. I could see a small case for support the rpm or deb, although it seems like the majority of people are ok with a single install path 🤷‍♂ 

If you'd like to contribute, you're more than welcome!

**Comment by splunkbot9000** [comment]
Regardless of rpm vs. tgz. The playbook doesn't play very nice with RHEL and needs a few preparation steps to be included in your wrapper playbook in order to deploy to remote servers (metal or not). It also neglects things like ulimits and THP.

My biggest gripe is the expectation of a "daemon-reload" service be present on the machine. I've had to spoof this on RHEL with a very basic daemon-reload script that does exactly that.

I hope to contribute where I can. I'm just unsure how to go about it. This would be my first go round contributing to a public repo.

**Comment by nwang92** [comment]
Closing this since https://github.com/splunk/splunk-ansible/pull/201 was merged
