### ISSUE TITLE
Another instance of assumption that same password is used everywhere

### ISSUE THREAD

**Issue by gregwhorley** [splunk/splunk-ansible#222]
Similar use case to #206 where a splunk image is spun up with a standalone role that connects to a license master. The [ansible task](https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/set_as_license_slave.yml#L3) calls [another task](https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/wait_for_splunk_instance.yml#L7) that performs a http request to the license master URL using the splunk install's own admin password. This fails in our environment because our license master container has a different admin password set.

**Comment by nwang92** [comment]
+1, definitely see this being useful. There are assumptions made here, including admin credentials but also standard ports. I think we could feasibly modify our current inventory variable schema with something like:
```
env:
  - name: SPLUNK_CLUSTER_MASTER_URL
     value: admin:password@master
```

This likely won't scale out for things like non-standard ports (especially since certain Splunk commands rely on other ports besides the management port 8089) but it should suffice to support different admin access across different roles?

cc @arctan5x

**Comment by nwang92** [comment]
Closing this because I believe https://github.com/splunk/splunk-ansible/pull/388/fixes this problem. I believe the only thing required for one Splunk instance to communicate to another is that the same pass4SymmKey is shared across both hosts. There's already a default one shipped in Splunk Enterprise, so unless it was manually changed it should just work.
