### ISSUE TITLE
Indexer discovery not working with SHC + IDXC

### ISSUE THREAD

**Issue by splunkbot9000** [splunk/splunk-ansible#252]
The indexer discovery pass4symmkey is not properly synchronized between the master instance and the SHC. I've had to force a shared splunk.secret to get forwarding to work from the SHC.

**Comment by nwang92** [comment]
I believe that's expected, particularly in a distributed environment. Since the splunk.secret is used to encrypt/decrypt all the sensitive password information in config files, if some instances start with different secrets you will likely brick a lot of internal Splunk-to-Splunk networking.

When these plays are used for the docker-splunk project, we actually recommend creating a single `default.yml` file that has a consistent set of values for passwords, secrets, etc. That ways all instances of a deployment have the same shared context to properly bring up a distributed environment.

Guessing that if you're hitting this issue, you're likely using splunk-ansible on it's own to provision bare metal/VMs?

**Comment by splunkbot9000** [comment]
Yes, and you helped fix the splunk.secret issue earlier by enabling splunk.secret via ENV vars. I can at least specify a shared secret this way and avoid storing it in default.yml. I haven't had a change to test the behavior so far but I believe that could potentially solve this issue.

**Comment by nwang92** [comment]
I'm going to close this issue then, but please re-open if it still does not solve your use-case. Thanks!
