### ISSUE TITLE
In a cluster env S2S inputs must not be enabled on a indexer directly

### ISSUE THREAD

**Issue by rfaircloth-splunk** [splunk/splunk-ansible#292]
This can allow for data loss when inputs are created prior to deployment of indexes.conf from master

**Comment by bb03** [comment]
Thanks @rfaircloth-splunk, we will follow up with you about what you observed and the correct fix.

**Comment by nwang92** [comment]
Closing this because we do need to open up s2s traffic on indexers directly in order to forward cluster master internal logs to the indexer tier: https://docs.splunk.com/Documentation/Splunk/latest/Indexer/Forwardmasterdata

It's definitely a best-practice to not rely on s2s inputs on indexers directly when they are part of a indexer cluster though.
