### ISSUE TITLE
Need index configuration with HEC

### ISSUE THREAD

**Issue by agarwalankitnyu** [splunk/splunk-ansible#293]
Current if I set the SPLUNK_HEC_TOKEN environment variable, it stets up hec just fine, but there is no option to configure the token with an index.

**Comment by bb03** [comment]
Hi @agarwalankitnyu,
  One of the things that you might be able to try is to run a custom ansible play using the SPLUNK_ANSIBLE_POST_TASKS environment variable and using the ini file module https://docs.ansible.com/ansible/latest/modules/ini_file_module.html

This should allow you to modify the index value of the HEC Token, though you will need to restart Splunk.

**Comment by nwang92** [comment]
Out of the box it should route the data to `index=main`, but if you're trying to send data to a separate index that is not part of the default Splunk indexes, you will likely need both an `indexes.conf` to setup the index + an `inputs.conf` for the HEC token/input itself.

If one exists without the other, your data ingest pipeline will likely be broken. In this case, I'd actually recommend you bundle both of these conf's up into an "app" and install it via `SPLUNK_APPS_URL` because as mentioned above, they are very co-dependent. But if your use case is different, please let me know and we can prioritize this.

**Comment by agarwalankitnyu** [comment]
Hi,
Thanks for all of your responses. I was able to handle this issue the other
way. When logging in python, I mentioned over there what index to log the
errors to, and that worked just fine. No need to modify the HEC index as
this satisfied our needs.

**Comment by bb03** [comment]
Closing this issue since @agarwalankitnyu found an acceptable solution.
