### ISSUE TITLE
Cluster Master race condition

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#35]
There seems to be a race condition with the [Apply the cluster bundle to the Splunk cluster master ](https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_cluster_master/tasks/main.yml#L63) task. If the indexers haven't completed booting, this will fail. I think this need a retry.

**Comment by jmervine** [comment]
On the plus side, with kubernetes, if it fails, it will attempt to restart it until they're available, so perhaps that enough. Your call. =D

**Comment by lephino** [comment]
Looking back at this, this could also be based on the amount of apps you push in the first bundle push.    Making me think I should really add the play logic in here for master-apps, and doing smaller pushes.

**Comment by jmervine** [comment]
Maybe. The app bundle isn't huge, two apps with just a few files at the moment. But I don't really know how the internals work.

👍 on support master-apps.

The larger question is, how do you want to support retries and failure loops. Do you want ansible to handle it, retrying until the indexers are available, or do you want to require that the user launch the indexers first, and then the cluster master in a non-k8s setup, and rely on k8s to crash loop until everything available.

I tend to prefer the idea of ansible handling retries, at least up to the default.yml specified retry limit for all the things.

**Comment by lephino** [comment]
For those that stumble across this issue and would like to comment on a discussion point, please see: 
https://github.com/splunk/splunk-ansible/pull/83

**Comment by jmervine** [comment]
I’m not sure that the this issue is that same as the one mentioned in #83. That is with the deployer, while this is specific to the cluster master.

**Comment by lephino** [comment]
It’s not; it’s similar and was looking to draw attention to the pr since most people won’t go that deep.

**Comment by nwang92** [comment]
I'm going to close this since this issue is stale, and it seems the problem is likely resolved because the apply bundle task does include retries and should not fail even when the bundle push does not complete in the given timeframe: https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_cluster_master/tasks/apply_cluster_bundle.yml

**Comment by martinr103** [comment]
Unfortunately the problem is not resolved.
And it is not the matter of the task including retries.
Even if there is the `retries:` option included - those retries are NOT executed.
Instead, the task fails immediately, if the "rolling restart of the peers" is in progress.

As I understand it - the problem is, that the process of "bootstrapping" the clustermanager already triggers (!) some restarts of the related indexers, and if those restarts of indexers execute very quickly, then the task "Apply cluster bundle" is able to continue.
But if those implicitly triggered indexer restarts take some time (because the indexers have large data to maintain) - then the task "Apply cluster bundle" is "too fast", and is executed while the "rolling restart" is still in progress.
This condition leads to an immediate exit with failure.

My local fix is to let the task wait some time, until the state "rolling restart in progress" is gone.
Fix proposal is to add line no. 35 as:
`until: splunk_cluster_bundle_result.stderr.find("Rolling restart of the peers is in progress") == -1`

This way the task attempts several retries, and does not exit immediately.

**Comment by cderocco5** [comment]
We need a way to skip the "apply cluster bundle" task too or just ignore the failure. Waiting for a rolling restart of splunk to finish could take hours depending on the size of your cluster.

**Comment by cderocco5** [comment]
> Unfortunately the problem is not resolved. And it is not the matter of the task including retries. Even if there is the `retries:` option included - those retries are NOT executed. Instead, the task fails immediately, if the "rolling restart of the peers" is in progress.
> 
> As I understand it - the problem is, that the process of "bootstrapping" the clustermanager already triggers (!) some restarts of the related indexers, and if those restarts of indexers execute very quickly, then the task "Apply cluster bundle" is able to continue. But if those implicitly triggered indexer restarts take some time (because the indexers have large data to maintain) - then the task "Apply cluster bundle" is "too fast", and is executed while the "rolling restart" is still in progress. This condition leads to an immediate exit with failure.
> 
> My local fix is to let the task wait some time, until the state "rolling restart in progress" is gone. Fix proposal is to add line no. 35 as: `until: splunk_cluster_bundle_result.stderr.find("Rolling restart of the peers is in progress") == -1`
> 
> This way the task attempts several retries, and does not exit immediately.


We need a way to skip the "apply cluster bundle" task too or just ignore the failure. Waiting for a rolling restart of Splunk to finish could take hours depending on the size of your cluster.

**Comment by martinr103** [comment]
> 
> We need a way to skip the "apply cluster bundle" task too or just ignore the failure. Waiting for a rolling restart of Splunk to finish could take hours depending on the size of your cluster.
Well, I don't know if skipping the task, or ignoring the failure is a good idea. You end up with an inconsistent cluster state (different bundle on the cluster manager , and different bundle on the peers)
By the way, if your rolling restart takes hours - then there is some other serious issue in the Splunk architecture, which should be solved in the first place. It can take minutes, but not hours.
