### ISSUE TITLE
Invalid key (rootCA) in inputs.conf/[sslConfig]

### ISSUE THREAD

**Issue by d3vzer0** [splunk/splunk-ansible#490]
Hi team,

I'm running the Splunk 8.0.4 docker image but it looks like that configuring s2s (via the defaults.yml) breaks the indexers. This happens when a valid indexes.conf is already present on the indexer and not when an indexes.conf doesn't exist yet.  We have the following s2s config in the default.yml:

```
  s2s:
    ca: "/opt/splunk/etc/auth/forwarders/ca.pem"
    cert: "/opt/splunk/etc/auth/forwarders/server.pem"
    enable: true
    port: 9997
    ssl: true
    password: XXXXX
```

When trying to run Splunk, the following notification appears:

```Invalid key in stanza [sslConfig] in /opt/splunk/etc/system/local/inputs.conf, line 9: rootCA  (value:  /opt/splunk/etc/auth/forwarders/ca.pem)```

After reading the docs (https://docs.splunk.com/Documentation/Splunk/8.0.4/Admin/Inputsconf) it seems that the rootCA key shouldn't even be inside the inputs.conf / sslConfig stanza in the first place. This is listed as a deprecated option. Could this be related or is this a totally different issue?

PS. inputs.conf is changed by the Ansible playbook to include:

```
[splunktcp-ssl:9997]
disabled = 0

[SSL]
serverCert = /opt/splunk/etc/auth/forwarders/server.pem
sslPassword = XXXXXXX

[sslConfig]
rootCA = /opt/splunk/etc/auth/forwarders/ca.pem
```

**Comment by d3vzer0** [comment]
Not sure if this is related, but...

The default branch for splunk-ansible is development. The development branch contains the incorrect configuration: https://github.com/splunk/splunk-ansible/blob/develop/roles/splunk_common/tasks/s2s/configure_splunktcp_ssl.yml

While looking looking at the master branch (which is not default): https://github.com/splunk/splunk-ansible/blob/0a424e66b95921c752e77e76fce4e787862fb1b2/roles/splunk_common/tasks/s2s/configure_splunktcp_ssl.yml it seems that the configuration is correct and matches what is written in the Splunk docs...

**Comment by d3vzer0** [comment]
Found it. The latest related merge reverted back the incorrect 'rootCA' configuration to inputs.conf:

https://github.com/splunk/splunk-ansible/commit/da4fe95ac82b444b9a98c3f7b1a21e504dd462bb

**Comment by nwang92** [comment]
Let me take a look - I believe the bug here is that `rootCA` should be in the `SSL` section of inputs.conf (although it is marked as deprecated).

I reverted this in order to broker the differences required for adding a custom Splunkd cert chain: https://github.com/splunk/splunk-ansible/pull/454/files. The TLDR of this if there are two options that modify the same key:
```
splunk:
  ...
  s2s:
    ca: /path/to/ca1.pem
  ssl:
    ca: /path/to/ca2.pem
```

In the end, only one can be written to `server.conf/[sslConfig]/sslRootCAPath`, and which ever one doesn't get persisted potentially breaks that respective feature. The default setting of `ca: null` also causes problems because the tasks attempt to revert back to certs generated by Splunk. 

I ended up moving to `rootCA` because (theoretically) that would support different cert chains for splunktcp-ssl and splunkd in isolation. I'm not sure if that is the intended use-case or not - maybe this is a question you can help answer :) Is it your expectation that splunktcp-ssl can be configured without changing the cert chain for the splunkd server itself? Or are you ok with/planning to add your own certs for everything within Splunk Enterprise?

I have no issues with changing this back to `server.conf/[sslConfig]/sslRootCAPath` and making a lot of warnings/caveats surrounding this in the docs, but I am a little wary of how it could negatively impact some user-experience (ex. enabling splunktcp-ssl breaks Splunkd, or vice versa).

**Comment by d3vzer0** [comment]
@nwang92 The choice to separate the two configurations is understandable :) We have a similar setup running where splunktcp-ssl is indeed configured differently than Splunkd itself. So if I understood correctly: the reason this configuration doesn't work in docker-splunk 8.0.4 is due to the location where the **rootCA** is configured for s2s, which is saved as inputs.conf/[sslConfig]/rootCA while this should be inputs.conf/[SSL]/rootCA?

**Comment by nwang92** [comment]
Correct, I made a PR here which should fix this: https://github.com/splunk/splunk-ansible/pull/492. I can publish a new `splunk/splunk:edge` image if you'd like to try it out.
