### ISSUE TITLE
Splunk secret playbook breaks when splunk.secret is supplied

### ISSUE THREAD

**Issue by arctan5x** [splunk/splunk-ansible#51]
Running any standalone provisioning breaks when splunk.secret is supplied.

**Comment by nwang92** [comment]
The problem here is mostly due to supporting this parameter when there's a good chance it will brick your Splunk installation. 

If you spin up a standalone with `splunk.secret` set, the initial `docker run` will work successfully. However, if you end up modifying the default.yml and change this secret, the next time your container restarts (assuming it preserves the volumes), splunkd fails to successfully start. This is because the pass set in this secret file is used to encrypt a lot of internal passphrases, so changing this will require all the pass4SymmKey/sslPasswords/etc. to be updated.

It seems like we'd need an additional routine/playbook to handle that if we do want to support this in the future, but for the immediate term I don't think we should expose this way of potentially breaking your splunk-on-docker cluster. 

For more information, see https://answers.splunk.com/answers/639815/what-is-the-splunksecret-file-and-is-it-possible-t.html

**Comment by nwang92** [comment]
Fixed in https://github.com/splunk/splunk-ansible/pull/52
