### ISSUE TITLE
First run / Upgrade logic

### ISSUE THREAD

**Issue by SkyKnightSKS** [splunk/splunk-ansible#59]
#47

Knowing when it is in either of those situations would allows us to avoid unnecessary steps.
It considerably improves the re-startup speed of containers and machines.

Initially I thought to:
check if exec exists && build exists --> upgrade
check if exec doesn't exists && build exists --> install

However, I did not see the different between the upgrade and install path, so I had changed it to 'first run'. The latest change in #47 makes it impossible to follow the upgrade path on non-docker machines.

**Comment by nwang92** [comment]
Seems like my change only looks for an existing bin/splunk executable, which would block the upgrade path you outlined. If I'm understanding correctly, you're using the same set of Ansible plays in a non-dockerized environment and you want the ability for site.yml to also perform the upgrade (along with the rest of the tasks)? Just for some context, are you using these Ansible plays in an EC2 AMI or something like that?

**Comment by dLabsMarijnB** [comment]
Exactly, I think it can perfectly handle both install and an upgrade.

We are using the Ansible in several different situations in production:
- Completely dockerized
- Half dockerized / half VMs on ESX
- VMs on ESX

**Comment by nwang92** [comment]
Got it, I took a closer look at this section and in order to support this use-case, I think it'd require some refactoring to proceed. The current set of ansible plays are designed to operate in the context of a container, where we do make the assumption that environments go down/come up "fresh" on their own.

In the case of porting this to VMs on ESX, those design patterns don't apply. For instance, the containers run site.yml initially on boot + on any restart. However, if you're running this on VMs, you can easily run site.yml once to get Splunk up and running. But dropping a new splunk.tgz in /tmp/ and running site.yml again with the expectation to cleanly upgrade would fail, as you'd immediately hit an issue with the splunk process already running.

Again not a technically difficult task, but I think this bit does involve more work than adding another file check when we consider the idempotency concerns of different environments.

**Comment by SkyKnightSKS** [comment]
Closed by #104
