### ISSUE TITLE
Rename splunk-ansible to splunk-ansible-docker

### ISSUE THREAD

**Issue by mason-splunk** [splunk/splunk-ansible#603]
I would like to request that this repository be renamed to `splunk-ansible-docker`. I think the current name of `splunk-ansible` is misleading, as this role only supports Splunk deployments within Docker containers. This is confusing to our customers as there is a [separate Ansible role published by Splunk](https://github.com/splunk/ansible-role-for-splunk) for managing Splunk deployments outside of Docker.

**Comment by nwang92** [comment]
I'm going to close this issue out - we currently have no intention of renaming this repository due to some dependencies on it. Additionally, I've worked with some customers/PS on using these playbooks outside of Docker and an overview of that work is captured here: https://github.com/splunk/splunk-ansible/tree/develop/docs/execution_patterns/remote
