### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by jmervine** [splunk/splunk-ansible#86]
> Note: This is a repost of https://github.com/splunk/docker-splunk/issues/116, but the issue is the same for this repo.

On hub.docker.com, there's a 7.2.3 release that was cut about a month ago. However, there's no git tag to match. It would be really helpful to be able to compare what's on hub.docker.com, with the current repo state. E.g.

https://github.com/splunk/splunk-ansible/compare/<version_tag>..develop

**Comment by nwang92** [comment]
Went through history and added tags that lined up with when we pushed images. There might be some issues with <=7.2.1 because we started to use "develop" for development instead of "master". Hopefully things should line up though. We also started incorporating git tagging with our release process going forward, so this should be smoother in the future.
